### ISSUE TITLE
Move the project under 4store organisation

### ISSUE THREAD

**Issue by berezovskyi** [4store/4store#148]
The project is not maintained under Garlik anyway and the 4store.github.io domain required a new organisation. So maybe it makes sense to move the whole project over there in the future. I added @swh as an owner of the new organisation.

**Comment by swh** [comment]
Agreed.

Is there a mechanism to move projects, or is it a case of cloning the repo and copying all the issues over?

**Comment by berezovskyi** [comment]
Yes, open Settings and at the very bottom of the page you will find:

![bildschirmfoto 2017-03-27 um 17 12 18](https://cloud.githubusercontent.com/assets/64734/24363578/8eb78e7e-1310-11e7-8256-fa96e59da22d.png)

Use `4store` as the organisation.

**Comment by swh** [comment]
OK, done. I had to add the garlik user as a collaborator for the 4store, then it was possible.

Luckily I remembered the password!
