### ISSUE TITLE
N-Quads / Multiple graphs

### ISSUE THREAD

**Issue by rwe87ywuifhwuirewhui** [4store/4store#159]
Does 4store support multiple graphs with `SELECT ... FROM <..>` queries, or is it only a single giant graph?

**Comment by swh** [comment]
It has multiple graphs, and is heavily optimised for sub-graph spanning queries.

The default graph is the union of all the subgraphs though.

IIRC, FROM <a>, <b>... uses the same optimiser path as
GRAPH ?g { XXX } WHERE ?g = <a> || ?g = <b>

**Comment by rwe87ywuifhwuirewhui** [comment]
thanks
