### ISSUE TITLE
What is a segment?

### ISSUE THREAD

**Issue by rwe87ywuifhwuirewhui** [4store/4store#160]
```
--segments
        The number of segments in the cluster. The default is 2. We recommend one for each
        CPU core in the cluster as a good starting point. Higher numbers tend to consume
        more resources, but may result in increased performance.
```

I'm having troubles understanding what a "segment" is. I also can't seem to find documentation about this. Could somebody please explain what is a 4store segment?

**Comment by swh** [comment]
It’s a cluster segment, same thing as a shard. The index is split into N segments, distributed equally across the backend systems.

If you’re not running on a cluster, just use 2 or 4.

**Comment by rwe87ywuifhwuirewhui** [comment]
Basically a percentage of the total data that a node is willing to take? So if I have 2 nodes, one with `--segments 2` and the other with `--segments 8`, then the entire KB is divided into 10 segments, 2 of which will go to the first node, and 8 to the other node?

**Comment by swh** [comment]
The number of segments is a DB level setting, so you could have 8 in total, 6 on one node and 2 on another - though I wouldn't recommend it.

**Comment by swh** [comment]
There's a description of the segmentation scheme in this paper from a few years ago:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.368.5588&rep=rep1&type=pdf
