### ISSUE TITLE
Query to list graphs doesn't work

### ISSUE THREAD

**Issue by rwe87ywuifhwuirewhui** [4store/4store#161]
This query always returns zero results

`SELECT ?g WHERE { GRAPH ?g {} }`

but it should return a list of available graphs (models) instead.

Is this on purpose, a missing feature, or a bug?

**Comment by swh** [comment]
I don't remember to be honest.

What does
   ```SELECT DISTINCT ?g WHERE { GRAPH ?g { ?s ?p ?o } }```
give you?

**Comment by swh** [comment]
4store is not SPARQL 1.1 compliant, it's somewhere between 1.0 and 1.1

**Comment by rwe87ywuifhwuirewhui** [comment]
> What does
> SELECT DISTINCT ?g WHERE { GRAPH ?g { ?s ?p ?o } }
> give you?

This worked, it returned the list of graphs. Thanks!
